/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include<stdio.h>
#include<stdint.h>

int main(void)
{
	uint32_t *pClkCtrlReg = (uint32_t*)0x40023830;
	uint32_t *pPortDModeReg = (uint32_t*)0x40020C00;
	uint32_t *pPortDOutReg = (uint32_t*)0x40020C14;

	//1. enable the clock for GPOID peripheral in the AHB1ENR

	*pClkCtrlReg |= 0x08;

	//2. configure the mode of the IO pin as output
	//a. clear the 24th and 25th bit positions
	*pPortDModeReg &= 0x00FFFFFF;
	//b. make 24th bit position as 1 (SET)
	*pPortDModeReg |= 0x55000000;

	//3. SET 12th bit of the output data register to make I/O pin-12 HIGH
	*pPortDOutReg |= 0xF000;


	while(1);
}
